name: 'Jenkins Job'
description: 'Interact with Jenkins'
author: 'Marek Lotocki'

# branding:
#   icon: 'heart'
#   color: 'red'

inputs:
  url:
    description: 'Full url to the Jenkins instance'
    required: true
  username:
    description: 'Name of the user which will be use to connect to the Jenkins'
    required: true
  token:
    description: 'Token for the user'
    required: true
  crumbRequired:
    description: 'Does Jenkins required crumb'
    required: false
    default: false
  job:
    description: 'Name of the job to run'
    required: true
  params:
    description: 'Jenkins job parameters'
    required: false
outputs:
  state:
    description: 'State of the Jenkins job'

runs:
  using: node16
  main: dist/index.js
