name: 'Jenkins Job'
description: 'Interact with Jenkins'
author: 'Marek Lotocki'

# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

outputs:
  state:
    description: 'State of the Jenkins job'

runs:
  using: node20
  main: dist/index.js
