name: Test
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    test:
        name: Test
        runs-on: self-hosted
        steps:
            - name: Get the sources
              uses: actions/checkout@v4
            - name: Get Jenkins crumb
              uses: ./
              with: 
                url: http://localhost:8080
                username: github
                token: 1171f87efdff17f82c4828f84b794f473c

