name: Test
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    test:
        name: Test
        runs-on: self-hosted
        steps:
            - name: Get the sources
              uses: actions/checkout@v4
            - name: Create something
              id: get-output
              uses: ./
              with: 
                url: http://localhost:8080/
                username: github_service
                token: 11ac6d598f492051a9a1c7810754fbe9b8
            - name: Print output
              run: echo ${{steps.get-output.outputs.state}}
