name: Test
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    test:
        name: Test
        runs-on: self-hosted
        steps:
            - name: Get the sources
              uses: actions/checkout@v4
            - name: Run Jenkins job
              uses: ./
              with: 
                url: http://localhost:8080
                username: github
                token: ${{ secrets.JENKINS_TOKEN}}
                job: TestPipelineWithParams
                crumbRequired: true
                params: '{Repo: xyz}'

